# Generated by Django 5.1.6 on 2025-03-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerprofile',
            name='preferred_products',
        ),
        migrations.AddField(
            model_name='consumerprofile',
            name='preferred_products',
            field=models.ManyToManyField(blank=True, related_name='consumers', to='products.product'),
        ),
    ]
