# Generated by Django 5.1.6 on 2025-03-04 15:00

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='farmerprofile',
            index=django.contrib.postgres.indexes.GinIndex(fields=['farm_name'], name='idx_farm_name', opclasses=['gin_trgm_ops']),
        ),
    ]
